import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0f131c",
        foreground: "#dfe2ef",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "on-error": "#690005",
        "on-surface": "#dfe2ef",
        "surface-container-lowest": "#0a0e17",
        "on-primary": "#002e6a",
        secondary: "#4edea3",
        tertiary: "#ffb3ac",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-container": "#00311f",
        "primary-container": "#4d8eff",
        "secondary-fixed-dim": "#4edea3",
        surface: "#0f131c",
        primary: "#adc6ff",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004395",
        error: "#ffb4ab",
        "surface-dim": "#0f131c",
        "tertiary-fixed": "#ffdad6",
        "surface-bright": "#353943",
        "surface-container-low": "#181c25",
        "on-primary-fixed": "#001a42",
        "on-tertiary": "#680008",
        "surface-tint": "#adc6ff",
        "on-background": "#dfe2ef",
        "on-tertiary-fixed": "#410003",
        "outline-variant": "#424754",
        "inverse-primary": "#005ac2",
        "tertiary-container": "#ff544e",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#930010",
        "surface-container-high": "#262a34",
        outline: "#8c909f",
        "tertiary-fixed-dim": "#ffb3ac",
        "inverse-on-surface": "#2c303a",
        "surface-container": "#1c2029",
        "on-primary-container": "#00285d",
        "surface-container-highest": "#31353f",
        "primary-fixed-dim": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-container": "#5c0006",
        "secondary-container": "#00a572",
        "on-surface-variant": "#c2c6d6",
        "surface-variant": "#31353f",
        "inverse-surface": "#dfe2ef",
        "on-secondary": "#003824",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
